---
guest_qemu_agent_install_enabled: false
guest_qemu_agent_install_linux_package_name: qemu-guest-agent
guest_qemu_agent_install_linux_service_name: qemu-guest-agent
guest_qemu_agent_install_windows_service_name: QEMU-GA
guest_qemu_agent_install_windows_arch: x86_64
guest_qemu_agent_install_windows_package_base_url: https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/latest-qemu-ga
guest_qemu_agent_install_windows_package_path: >-
  {{
    guest_qemu_agent_install_windows_package_base_url
    ~ '/qemu-ga-'
    ~ guest_qemu_agent_install_windows_arch
    ~ '.msi'
  }}
guest_qemu_agent_install_windows_package_arguments: /qn /norestart
