---
freeipa_access_model_enabled: true
freeipa_access_model_admin_principal: "{{ freeipa_admin_principal | default('admin') }}"
freeipa_access_model_admin_password: "{{ freeipa_admin_password | default('') }}"
freeipa_access_model_api_context: "{{ freeipa_api_context | default('server') }}"
freeipa_access_model_manage_inventory_group_host_membership: true
freeipa_access_model_user_groups: "{{ freeipa_user_groups | default([]) }}"
freeipa_access_model_hostgroups: "{{ freeipa_hostgroups | default([]) }}"
freeipa_access_model_hbac_rules: "{{ freeipa_hbac_rules | default([]) }}"
freeipa_access_model_sudo_rules: "{{ freeipa_sudo_rules | default([]) }}"
freeipa_access_model_manage_default_login_shell: true
freeipa_access_model_default_login_shell: "{{ freeipa_default_login_shell | default('/bin/bash') }}"
freeipa_access_model_manage_group_member_login_shell: true
freeipa_access_model_login_shell_groups: >-
  {{
    freeipa_login_shell_groups
    | default(
        (
          freeipa_access_model_user_groups
          | map(attribute='name')
          | select('equalto', 'linux-ssh-admins')
          | list
        ),
        true
      )
  }}
