---
linux_freeipa_enroll_enabled: true
linux_freeipa_enroll_serial: 10
linux_freeipa_enroll_max_fail_percentage: 0
linux_freeipa_enroll_manage_hostname: false
linux_ipa_servers: []
linux_ipaadmin_principal: "{{ freeipa_admin_principal }}"
linux_ipaadmin_password: "{{ freeipa_admin_password }}"
linux_ipaclient_mkhomedir: true
linux_ipaclient_force_join: false
linux_ipaclient_no_dns_lookup: true
linux_ipaclient_no_sudo: false
linux_ipasssd_permit: false
linux_ipaclient_configure_dns_resolver: false
linux_ipaclient_dns_servers: []
linux_ipaclient_install_packages: true
linux_ipa_manage_etc_hosts: false
linux_ipa_etc_hosts_entries: []
