---
- name: Ensure FreeIPA user groups are present
  freeipa.ansible_freeipa.ipagroup:
    ipaadmin_principal: "{{ freeipa_access_model_admin_principal }}"
    ipaadmin_password: "{{ freeipa_access_model_admin_password }}"
    ipaapi_context: "{{ freeipa_access_model_api_context }}"
    name: "{{ item.name }}"
    description: "{{ item.description | default(omit) }}"
    gidnumber: "{{ item.gidnumber | default(omit) }}"
    user: >-
      {{
        item.user
        if (
          (item.user is defined)
          and
          (
            (
              item.user is sequence
              and item.user is not string
              and (item.user | length > 0)
            )
            or
            (
              item.user is string
              and (item.user | trim | length > 0)
            )
          )
        )
        else omit
      }}
    group: >-
      {{
        item.group
        if (
          (item.group is defined)
          and
          (
            (
              item.group is sequence
              and item.group is not string
              and (item.group | length > 0)
            )
            or
            (
              item.group is string
              and (item.group | trim | length > 0)
            )
          )
        )
        else omit
      }}
    external: "{{ item.external | default(omit) }}"
    nonposix: "{{ item.nonposix | default(omit) }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ freeipa_access_model_user_groups }}"
  loop_control:
    label: "{{ item.name }}"
  no_log: true
