---
- name: Ensure FreeIPA HBAC rules are present
  freeipa.ansible_freeipa.ipahbacrule:
    ipaadmin_principal: "{{ freeipa_admin_principal }}"
    ipaadmin_password: "{{ freeipa_admin_password }}"
    ipaapi_context: "{{ freeipa_api_context }}"
    name: "{{ item.name }}"
    description: "{{ item.description | default(omit) }}"
    usercategory: "{{ item.usercategory | default(omit) }}"
    hostcategory: "{{ item.hostcategory | default(omit) }}"
    servicecategory: "{{ item.servicecategory | default(omit) }}"
    host: "{{ item.host | default(omit) }}"
    hostgroup: "{{ item.hostgroup | default(omit) }}"
    hbacsvc: "{{ item.hbacsvc | default(omit) }}"
    hbacsvcgroup: "{{ item.hbacsvcgroup | default(omit) }}"
    user: "{{ item.user | default(omit) }}"
    group: "{{ item.group | default(omit) }}"
    action: "{{ item.action | default('hbacrule') }}"
    state: >-
      {{
        (
          item.action | default('hbacrule') == 'hbacrule'
          and item.state | default('enabled') in ['enabled', 'disabled']
        ) | ternary('present', item.state | default('present'))
      }}
  loop: "{{ freeipa_hbac_rules }}"
  loop_control:
    label: "{{ item.name }}"
  no_log: true

- name: Ensure FreeIPA HBAC rules are enabled or disabled as requested
  freeipa.ansible_freeipa.ipahbacrule:
    ipaadmin_principal: "{{ freeipa_admin_principal }}"
    ipaadmin_password: "{{ freeipa_admin_password }}"
    ipaapi_context: "{{ freeipa_api_context }}"
    name: "{{ item.name }}"
    action: "{{ item.action | default('hbacrule') }}"
    state: "{{ item.state | default('enabled') }}"
  loop: "{{ freeipa_hbac_rules }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - not ansible_check_mode
    - item.action | default('hbacrule') == 'hbacrule'
    - item.state | default('enabled') in ['enabled', 'disabled']
  no_log: true
